import Link from 'next/link';
import { CheckCircle } from 'lucide-react';
import { Container, Section } from '@/components/Layout';
import { Button } from '@/components/Button';
import { prisma } from '@/lib/prisma';
import { formatDate, formatPrice } from '@/lib/utils';
import { OrderConfirmationNotice } from '@/components/OrderConfirmationNotice';

export default async function OrderConfirmationPage({ searchParams }: { searchParams: Promise<{ orderId?: string }> }) {
  const { orderId } = await searchParams;
  const order = orderId ? await prisma.order.findUnique({ where: { id: orderId }, include: { items: true, shippingAddress: true } }) : null;
  if (!order || !order.shippingAddress) return <Section className="min-h-screen py-32"><Container className="max-w-xl text-center"><h1>We couldn’t find that order.</h1><p className="mt-4 text-svnctm-charcoal/65">Please return to checkout and try again.</p><Link href="/checkout" className="mt-8 inline-block rounded-full bg-svnctm-charcoal px-6 py-3 text-sm font-semibold text-white">Return to checkout</Link></Container></Section>;
  const address = order.shippingAddress;
  return <><OrderConfirmationNotice orderNumber={order.orderNumber} /><Section className="bg-svnctm-pink-light py-20"><Container><div className="text-center"><CheckCircle size={60} className="mx-auto text-svnctm-pink" /><p className="eyebrow mt-5">Order received</p><h1 className="mt-3 text-4xl tracking-tight">Your ritual is on its way.</h1><p className="mx-auto mt-4 max-w-xl text-svnctm-charcoal/70">Thank you, {address.fullName}. We’ve received your order and will send delivery updates to WhatsApp.</p></div></Container></Section><Section className="bg-white"><Container><div className="grid gap-12 md:grid-cols-2"><div className="space-y-5"><h2>Order confirmation</h2><div className="grid gap-4 sm:grid-cols-2"><Info label="Order number" value={order.orderNumber} /><Info label="Order date" value={formatDate(order.createdAt)} /><Info label="Customer" value={address.fullName} /><Info label="Email" value={address.email} /></div><div className="rounded-brand bg-svnctm-white-warm p-5"><p className="text-xs font-semibold uppercase tracking-wide text-svnctm-charcoal/50">Shipping address</p><div className="mt-3 text-sm leading-6 text-svnctm-charcoal"><p>{address.fullName}</p><p>{address.address}{address.apartment ? `, ${address.apartment}` : ''}</p><p>{address.city}, {address.state} {address.postalCode}</p><p>India · {address.phone}</p></div></div></div><div><h2>Order summary</h2><div className="mt-5 rounded-brand bg-svnctm-white-warm p-5">{order.items.map((item) => <div key={item.id} className="flex justify-between border-b border-svnctm-charcoal/10 py-4 first:pt-0"><div><p className="font-medium">{item.name}</p><p className="mt-1 text-sm text-svnctm-charcoal/60">Quantity: {item.quantity}</p></div><p className="font-semibold">{formatPrice(item.total)}</p></div>)}<div className="space-y-2 pt-4 text-sm"><Row label="Subtotal" value={formatPrice(order.subtotal)} /><Row label="Shipping" value={order.shippingCost ? formatPrice(order.shippingCost) : 'Free'} /><Row label="Tax" value={formatPrice(order.tax)} /><div className="flex justify-between border-t border-svnctm-charcoal/15 pt-3 text-base font-semibold"><span>Total</span><span>{formatPrice(order.total)}</span></div></div></div><p className="mt-4 text-xs text-svnctm-charcoal/55">Payment status: {order.paymentStatus.replace('_', ' ').toLowerCase()}. Delivery updates are queued for WhatsApp.</p></div></div></Container></Section><Section className="bg-svnctm-white-warm py-16"><Container className="text-center"><h2 className="text-3xl">What’s next?</h2><p className="mt-3 text-svnctm-charcoal/65">Our team will prepare your order with care.</p><Button className="mt-7"><Link href="/shop">Continue shopping</Link></Button></Container></Section></>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-brand bg-svnctm-white-warm p-4"><p className="text-xs font-semibold uppercase tracking-wide text-svnctm-charcoal/50">{label}</p><p className="mt-2 break-words text-sm font-medium text-svnctm-charcoal">{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between text-svnctm-charcoal/65"><span>{label}</span><span>{value}</span></div>; }
