import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Gift, Leaf, MoveRight, ShieldCheck, Sparkles, Truck } from 'lucide-react';
import { Container, Section } from '@/components/Layout';
import { Button } from '@/components/Button';
import { ProductCard } from '@/components/ProductCard';

const featuredProducts = [
  { id: '1', name: 'Soft Sanctuary Candle', price: 899, comparePrice: 1200, image: '/images/sanctum-hero.png', scent: 'Lavender & Sandalwood', slug: 'soft-sanctuary-candle' },
  { id: '2', name: 'Evening Ritual Candle', price: 899, image: '/images/sanctum-hero.png', scent: 'Cedarwood & Amber', slug: 'evening-ritual-candle' },
  { id: '3', name: 'Quiet Moment Candle', price: 1299, image: '/images/sanctum-hero.png', scent: 'Rose & Bergamot', slug: 'quiet-moment-candle' },
  { id: '4', name: 'Home Sanctuary Diffuser', price: 1499, image: '/images/sanctum-hero.png', scent: 'Jasmine & Musk', slug: 'home-sanctuary-diffuser' },
];

export default function Home() {
  return <>
    <Section noPadding className="relative min-h-[calc(100svh-73px)] overflow-hidden bg-[#eee7e2]"><div className="absolute inset-0 hero-grain" /><Container className="relative grid min-h-[calc(100svh-73px)] items-center gap-10 py-16 lg:grid-cols-[.9fr_1.1fr] lg:py-10"><div className="relative z-10 max-w-xl animate-fade-up"><p className="mb-6 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.22em] text-svnctm-pink"><Sparkles size={14} /> Design-led home fragrance</p><h1 className="text-5xl font-medium leading-[.96] tracking-[-.055em] text-svnctm-charcoal sm:text-6xl lg:text-8xl">Make room<br />for ritual.</h1><p className="mt-7 max-w-md text-lg leading-8 text-svnctm-charcoal/70">Objects of calm for your most lived-in spaces. Made to look beautiful before they are even lit.</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" className="shadow-lg shadow-svnctm-pink/20"><Link href="/shop" className="flex items-center gap-2">Shop the collection <ArrowRight size={18} /></Link></Button><Link href="/about" className="inline-flex items-center gap-2 px-5 py-4 text-sm font-semibold text-svnctm-charcoal hover:text-svnctm-pink">Our philosophy <MoveRight size={17} /></Link></div><div className="mt-12 flex gap-8 border-t border-svnctm-charcoal/15 pt-6 text-xs text-svnctm-charcoal/65"><span><b className="block text-lg text-svnctm-charcoal">48h</b>burn time</span><span><b className="block text-lg text-svnctm-charcoal">100%</b>soy wax</span><span><b className="block text-lg text-svnctm-charcoal">India</b>poured by hand</span></div></div><div className="relative h-[48vh] min-h-[390px] overflow-hidden rounded-[2rem] shadow-2xl shadow-svnctm-charcoal/15 lg:h-[76vh] animate-fade-in"><Image src="/images/sanctum-hero.png" alt="A sculptural SVNCTM candle in a warm, minimalist interior" fill priority sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-tr from-svnctm-charcoal/30 via-transparent to-transparent" /><div className="absolute bottom-5 left-5 rounded-full bg-white/90 px-4 py-2 text-xs font-semibold text-svnctm-charcoal backdrop-blur">The Sanctum Collection · 2026</div></div></Container></Section>
    <section className="border-y border-svnctm-charcoal/10 bg-white py-4"><Container className="grid grid-cols-1 gap-3 text-center text-xs font-semibold uppercase tracking-[.15em] text-svnctm-charcoal/60 sm:grid-cols-3"><span className="flex items-center justify-center gap-2"><Truck size={15} /> Complimentary shipping over ₹1,500</span><span className="flex items-center justify-center gap-2"><Leaf size={15} /> Thoughtfully sourced materials</span><span className="flex items-center justify-center gap-2"><Gift size={15} /> Gift-ready, always</span></Container></section>
    <Section className="bg-white py-24 lg:py-32"><Container><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">The edit</p><h2 className="mt-3 text-4xl tracking-tight lg:text-5xl">Designed to belong.</h2></div><Link href="/shop" className="group inline-flex items-center gap-2 text-sm font-semibold">View all objects <ArrowRight size={17} className="transition-transform group-hover:translate-x-1" /></Link></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{featuredProducts.map((product) => <ProductCard key={product.id} {...product} />)}</div></Container></Section>
    <Section className="bg-svnctm-charcoal py-24 text-white lg:py-32"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-svnctm-pink-light">A slower kind of luxury</p><h2 className="mt-4 text-4xl leading-tight tracking-tight lg:text-5xl">The ritual is the point.</h2><p className="mt-6 max-w-sm leading-7 text-white/65">Fragrance that lives softly in a room and design that earns its place there.</p></div><div className="grid gap-6 sm:grid-cols-3">{[['01','Set the scene','A considered object changes the feeling of a room.'],['02','Light slowly','Let the first burn create an even, lasting ritual.'],['03','Stay awhile','Fragrance unfolds quietly—without asking for attention.']].map(([n,t,c]) => <div key={n} className="border-t border-white/20 pt-5"><span className="text-xs tracking-[.2em] text-svnctm-pink-light">{n}</span><h3 className="mt-8 text-xl text-white">{t}</h3><p className="mt-3 text-sm leading-6 text-white/60">{c}</p></div>)}</div></div></Container></Section>
    <Section className="bg-svnctm-lavender/35 py-24"><Container><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">A note from us</p><h2 className="mt-4 text-4xl tracking-tight lg:text-5xl">Make the everyday feel considered.</h2><p className="mt-5 text-lg leading-8 text-svnctm-charcoal/70">Receive first access to new objects, private rituals, and small moments of inspiration.</p><form className="mx-auto mt-8 flex max-w-md gap-2 rounded-full bg-white p-1.5 shadow-soft"><input aria-label="Email address" type="email" required placeholder="Your email address" className="min-w-0 flex-1 bg-transparent px-4 text-sm outline-none" /><button className="rounded-full bg-svnctm-charcoal px-5 py-3 text-sm font-semibold text-white transition-transform hover:scale-[1.03]">Join us</button></form><div className="mt-6 flex justify-center gap-5 text-xs text-svnctm-charcoal/60"><span className="flex items-center gap-1"><ShieldCheck size={14} /> No noise, ever</span><span>Unsubscribe anytime</span></div></div></Container></Section>
  </>;
}
