import Link from 'next/link';
import { ArrowLeft, Download, Plus, Search, SlidersHorizontal } from 'lucide-react';

const sections: Record<string, { title: string; description: string; action: string; columns: string[] }> = {
  orders: { title: 'Orders', description: 'Track fulfilment, payments, and customer delivery status.', action: 'Create order', columns: ['Order', 'Customer', 'Status', 'Total'] },
  products: { title: 'Products', description: 'Build and maintain a considered, accurate product catalogue.', action: 'Add product', columns: ['Product', 'SKU', 'Inventory', 'Price'] },
  customers: { title: 'Customers', description: 'View customer history, preferences, and lifetime value.', action: 'Add customer', columns: ['Customer', 'Orders', 'Last order', 'Lifetime value'] },
  inventory: { title: 'Inventory', description: 'Keep stock levels accurate and receive low-stock alerts.', action: 'Adjust stock', columns: ['Product', 'SKU', 'On hand', 'Threshold'] },
  coupons: { title: 'Offers', description: 'Create intentional promotions without losing sight of margin.', action: 'Create offer', columns: ['Code', 'Value', 'Redemptions', 'Expires'] },
  settings: { title: 'Store settings', description: 'Control customer-facing details, payments, and notifications.', action: 'Save changes', columns: ['Setting', 'Value', 'Updated', 'Owner'] },
};

export default async function AdminSection({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params;
  const config = sections[section] ?? { title: 'Management', description: 'Manage your store operations in one place.', action: 'Add item', columns: ['Name', 'Status', 'Updated', 'Actions'] };
  return <main className="min-h-screen bg-svnctm-white-warm px-4 py-8 sm:px-8"><div className="mx-auto max-w-7xl"><Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-svnctm-charcoal/65 hover:text-svnctm-pink"><ArrowLeft size={16} /> Dashboard</Link><div className="mt-8 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Store management</p><h1 className="mt-3 text-4xl tracking-tight text-svnctm-charcoal">{config.title}</h1><p className="mt-3 max-w-lg text-svnctm-charcoal/65">{config.description}</p></div><button className="inline-flex items-center justify-center gap-2 rounded-full bg-svnctm-charcoal px-5 py-3 text-sm font-semibold text-white transition-transform hover:scale-[1.02]"><Plus size={17} /> {config.action}</button></div><section className="mt-10 overflow-hidden rounded-[1.5rem] border border-svnctm-charcoal/10 bg-white shadow-soft"><div className="flex flex-col gap-4 border-b border-svnctm-charcoal/10 p-5 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl bg-svnctm-white-warm px-3"><Search size={17} className="text-svnctm-charcoal/50" /><input className="w-full bg-transparent py-3 text-sm outline-none" placeholder={`Search ${config.title.toLowerCase()}...`} /></label><div className="flex gap-2"><button className="inline-flex items-center gap-2 rounded-xl border border-svnctm-charcoal/10 px-4 text-sm font-medium"><SlidersHorizontal size={16} /> Filter</button><button className="inline-flex items-center gap-2 rounded-xl border border-svnctm-charcoal/10 px-4 text-sm font-medium"><Download size={16} /> Export</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-svnctm-white-warm text-xs uppercase tracking-[.12em] text-svnctm-charcoal/55"><tr>{config.columns.map((column) => <th key={column} className="px-6 py-4 font-semibold">{column}</th>)}</tr></thead><tbody><tr><td colSpan={config.columns.length} className="px-6 py-16 text-center"><p className="text-base font-semibold text-svnctm-charcoal">Your {config.title.toLowerCase()} will appear here.</p><p className="mt-2 text-sm text-svnctm-charcoal/60">The connected database is ready for your first record.</p></td></tr></tbody></table></div></section></div></main>;
}
